spring:
  application:
    name: db-conect

  datasource:
    url: jdbc:mysql://localhost:3306/bd_connect
    username: root
    password: dota123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect